import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import UIProvider from './UIProvider';
import SessionNextProvider from './SessionNextProvider';

const inter = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Base App Rizal V.1',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionNextProvider>
					<UIProvider>{children}</UIProvider>
				</SessionNextProvider>
			</body>
		</html>
	);
}
