import { Metadata } from 'next';
import ProfilDropdown from './components/ProfileDropdown';

export const metadata: Metadata = {
	title: 'Dashboard | Base.V1',
	description: 'Generated by create next app',
};

export default function page() {
	return (
		<main className="min-h-screen w-full p-10">
			<div className="flex justify-between">
				<h1 className="text-3xl font-bold">Dashboard</h1>
				<ProfilDropdown />
			</div>
		</main>
	);
}
